import type { Metadata } from "next";
import { ThemeProvider } from "server-mui";
import { createTheme } from "@mui/material/styles";
import "./globals.css";

export const metadata: Metadata = {
  title: "Server Mui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = createTheme({});

  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
